name: people

services:
  people.api:
    image: "elwark/people/api:${TAG:-latest}"
    build:
      context: .
      dockerfile: src/People.Api/Dockerfile

  people.worker:
    image: "elwark/people/worker:${TAG:-latest}"
    build:
      context: .
      dockerfile: src/People.Worker/Dockerfile
