version: '3.9'

services:
  people.api:
    image: "elwark/people/api:${TAG:-latest}"
    build:
      context: .
      dockerfile: src/People.Api/Dockerfile
  
  people.webhooks:
    image: "elwark/people/webhooks:${TAG:-latest}"
    build:
      context: .
      dockerfile: src/People.Webhooks/Dockerfile
