// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Elwark.People.Infrastructure.Migrations.IntegrationEventLogContext
{
    [DbContext(typeof(EventBus.Logging.EF.IntegrationEventLogContext))]
    internal class IntegrationEventLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Elwark.EventBus.Logging.EF.IntegrationEventLogEntry", b =>
            {
                b.Property<Guid>("EventId")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id")
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnName("content")
                    .HasColumnType("json");

                b.Property<DateTime>("CreationTime")
                    .HasColumnName("creation_time")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("EventTypeName")
                    .IsRequired()
                    .HasColumnName("event_type_name")
                    .HasColumnType("text");

                b.Property<int>("State")
                    .HasColumnName("state")
                    .HasColumnType("integer");

                b.Property<int>("TimesSent")
                    .HasColumnName("times_sent")
                    .HasColumnType("integer");

                b.HasKey("EventId");

                b.ToTable("integration_event_logs");
            });
#pragma warning restore 612, 618
        }
    }
}