//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elwark.People.Api.Infrastructure {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Elwark.People.Api.Infrastructure.ErrorMessageResources", typeof(ErrorMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IdentificationError_AlreadyRegistered {
            get {
                return ResourceManager.GetString("IdentificationError:AlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string IdentificationError_AlreadyAdded {
            get {
                return ResourceManager.GetString("IdentificationError:AlreadyAdded", resourceCulture);
            }
        }
        
        internal static string IdentificationError_AlreadyConfirmed {
            get {
                return ResourceManager.GetString("IdentificationError:AlreadyConfirmed", resourceCulture);
            }
        }
        
        internal static string IdentificationError_NotConfirmed {
            get {
                return ResourceManager.GetString("IdentificationError:NotConfirmed", resourceCulture);
            }
        }
        
        internal static string IdentificationError_NotFound {
            get {
                return ResourceManager.GetString("IdentificationError:NotFound", resourceCulture);
            }
        }
        
        internal static string IdentificationError_Forbidden {
            get {
                return ResourceManager.GetString("IdentificationError:Forbidden", resourceCulture);
            }
        }
        
        internal static string AccountError_Blocked {
            get {
                return ResourceManager.GetString("AccountError:Blocked", resourceCulture);
            }
        }
        
        internal static string AccountError_NotFound {
            get {
                return ResourceManager.GetString("AccountError:NotFound", resourceCulture);
            }
        }
        
        internal static string ConfirmationError_Invalid {
            get {
                return ResourceManager.GetString("ConfirmationError:Invalid", resourceCulture);
            }
        }
        
        internal static string ConfirmationError_Expired {
            get {
                return ResourceManager.GetString("ConfirmationError:Expired", resourceCulture);
            }
        }
        
        internal static string ConfirmationError_NotFound {
            get {
                return ResourceManager.GetString("ConfirmationError:NotFound", resourceCulture);
            }
        }
        
        internal static string ConfirmationError_NotMatch {
            get {
                return ResourceManager.GetString("ConfirmationError:NotMatch", resourceCulture);
            }
        }
        
        internal static string ConfirmationError_AlreadySent {
            get {
                return ResourceManager.GetString("ConfirmationError:AlreadySent", resourceCulture);
            }
        }
        
        internal static string CryptographyError_UnknownError {
            get {
                return ResourceManager.GetString("CryptographyError:UnknownError", resourceCulture);
            }
        }
        
        internal static string CryptographyError_InvalidFormat {
            get {
                return ResourceManager.GetString("CryptographyError:InvalidFormat", resourceCulture);
            }
        }
        
        internal static string CryptographyError_DecoderError {
            get {
                return ResourceManager.GetString("CryptographyError:DecoderError", resourceCulture);
            }
        }
        
        internal static string CryptographyError_JsonError {
            get {
                return ResourceManager.GetString("CryptographyError:JsonError", resourceCulture);
            }
        }
        
        internal static string NotificationError_Forbidden {
            get {
                return ResourceManager.GetString("NotificationError:Forbidden", resourceCulture);
            }
        }
        
        internal static string PasswordError_Empty {
            get {
                return ResourceManager.GetString("PasswordError:Empty", resourceCulture);
            }
        }
        
        internal static string PasswordError_NotSet {
            get {
                return ResourceManager.GetString("PasswordError:NotSet", resourceCulture);
            }
        }
        
        internal static string PasswordError_TooShort {
            get {
                return ResourceManager.GetString("PasswordError:TooShort", resourceCulture);
            }
        }
        
        internal static string PasswordError_RequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordError:RequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        internal static string PasswordError_RequiresDigit {
            get {
                return ResourceManager.GetString("PasswordError:RequiresDigit", resourceCulture);
            }
        }
        
        internal static string PasswordError_RequiresLower {
            get {
                return ResourceManager.GetString("PasswordError:RequiresLower", resourceCulture);
            }
        }
        
        internal static string PasswordError_RequiresUpper {
            get {
                return ResourceManager.GetString("PasswordError:RequiresUpper", resourceCulture);
            }
        }
        
        internal static string PasswordError_RequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordError:RequiresUniqueChars", resourceCulture);
            }
        }
        
        internal static string PasswordError_Mismatch {
            get {
                return ResourceManager.GetString("PasswordError:Mismatch", resourceCulture);
            }
        }
        
        internal static string PasswordError_Worst {
            get {
                return ResourceManager.GetString("PasswordError:Worst", resourceCulture);
            }
        }
        
        internal static string CommonError_ModelState {
            get {
                return ResourceManager.GetString("CommonError:ModelState", resourceCulture);
            }
        }
        
        internal static string CommonError_Unknown {
            get {
                return ResourceManager.GetString("CommonError:Unknown", resourceCulture);
            }
        }
        
        internal static string CommonError_Internal {
            get {
                return ResourceManager.GetString("CommonError:Internal", resourceCulture);
            }
        }
        
        internal static string CommonError_NotImplemented {
            get {
                return ResourceManager.GetString("CommonError:NotImplemented", resourceCulture);
            }
        }
        
        internal static string CommonError_NotSupported {
            get {
                return ResourceManager.GetString("CommonError:NotSupported", resourceCulture);
            }
        }
    }
}
