version: '3.7'

services:
        
  people.api:
    container_name: "elwark_people_api"
    image: elwark/people.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Elwark.People.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5001:80"
        
  people.background:
    container_name: "elwark_people_background"
    image: elwark/people.background:${TAG:-latest}
    build:
      context: .
      dockerfile: Elwark.People.Background/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5002:80"