version: '3.7'

networks:
  elwarknetwork:
    name: elwark_network

services:
  people.gateway:
    container_name: "people_gateway"
    image: "elwark/people-gateway:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Urls__Identity=http://identity
      - Urls__People.Api=http://people_api
      - Urls__Notification.Api=http://notification_api
    ports:
      - "5001:80"
    networks:
      - elwarknetwork

  people.api:
    container_name: "people_api"
    image: "elwark/people-api:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kestrel__EndPoints__Grpc__Url=http://+:80
      - Mongodb__ConnectionString=mongodb://mongo-1,mongo-2/?replicaSet=rs0
      - Kafka__Servers=broker:29092
    ports:
      - "5002:80"
    networks:
      - elwarknetwork

  people.worker:
    container_name: "people_worker"
    image: "elwark/people-worker:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Mongodb__ConnectionString=mongodb://mongo-1,mongo-2/?replicaSet=rs0
      - Kafka__Servers=broker:29092
    ports:
      - "5003:80"
    networks:
      - elwarknetwork

  people.notification:
    container_name: "notification_api"
    image: "elwark/notification-api:${TAG:-latest}"
    build:
      context: .
      dockerfile: Notification.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kestrel__EndPoints__Grpc__Url=http://+:80
      - Mongodb__ConnectionString=mongodb://mongo-1,mongo-2/?replicaSet=rs0
      - Kafka__Servers=broker:29092
    ports:
      - "5004:80"
    networks:
      - elwarknetwork
