version: '3.7'

networks:
  elwarknetwork:
    name: elwark_network

services:

  people.gateway:
    container_name: "people_gateway"
    image: "elwark/people-gateway:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Urls__Identity=http://identity
      - Urls__People.Account.Api=http://people_account_api
      - Urls__People.Notification.Api=http://people_notification_api
    ports:
      - "5001:80"
    networks:
      - elwarknetwork

  people.account:
    container_name: "people_account_api"
    image: "elwark/people-account-api:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Account.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kestrel__EndPoints__Grpc__Url=http://+:80
      - Mongodb__ConnectionString=mongodb://mongo-1,mongo-2/?replicaSet=rs0
      - Kafka__Servers=broker:29092
    ports:
      - "5002:80"
    networks:
      - elwarknetwork

  people.worker:
    container_name: "people_account_worker"
    image: "elwark/people-worker:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Account.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Mongodb__ConnectionString=mongodb://mongo-1,mongo-2/?replicaSet=rs0
      - Kafka__Servers=broker:29092
    ports:
      - "5003:80"
    networks:
      - elwarknetwork

  people.notification:
    container_name: "people_notification_api"
    image: "elwark/people-notification-api:${TAG:-latest}"
    build:
      context: .
      dockerfile: People.Notification.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kestrel__EndPoints__Grpc__Url=http://+:80
      - Mongodb__ConnectionString=mongodb://mongo-1,mongo-2/?replicaSet=rs0
      - Kafka__Servers=broker:29092
    ports:
      - "5004:80"
    networks:
      - elwarknetwork
