name: People api

on:
  push:
    branches: [ master ]

env:
  WORKING_DIRECTORY: ./src

jobs:
  people_api:
    name: Docker API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@master

      - name: Compose build people.api
        run: sudo -E docker-compose build people.api
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: bash
        env:
          TAG: latest
